### ISSUE TITLE
iOS 앱 테스팅을 위한 세팅

### ISSUE THREAD

**Issue by closer27** [papaolabs/papao-ios#2]
개발 중인 iOS 앱을 컨트리뷰터들의 디바이스에서 확인할 수 있도록 환경 세팅

**Comment by closer27** [comment]
TestFlight라는 테스팅 툴을 통해서 컨트리뷰터들의 디바이스에 설치가능한 환경을 조성할 예정입니다.

**Comment by closer27** [comment]
컨트리뷰터 분들께서는 각자의 모바일 폰에 [TestFlight](https://itunes.apple.com/kr/app/testflight/id899247664?mt=8) 앱을 설치하고 이 곳에 애플 이메일 계정을 적어주세요!

- closer527@gmail.com
- inhwan.lee@outlook.com

**Comment by easyaction** [comment]
ksy6808@gmail.com
입니다

**Comment by Hiiing** [comment]
zzx_0@naver.com
이요

**Comment by fractaliz2** [comment]
fractalize@gmail.com
입니다. 그럼 이만.
